---
resources:
- name: resource-web-app
  type: git
  source:
    uri: https://github.com/cloudfoundry-community/simple-go-web-app.git

- name: resource-tutorial
  type: git
  source:
    uri: {{git-url}}

- name: resource-deploy-web-app
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: true

jobs:
- name: job-deploy-app-with-manifest-change
  serial: true
  plan:
  - {get: resource-web-app, trigger: true}
  - task: update-manifest
    file: resource-tutorial/15_deploy_cloudfoundry_app/update-manifest-task.yml
    
  - put: resource-deploy-web-app
    params:
      manifest: cf-manifest/manifest.yml
      path: resource-web-app
