---
resources:
- name: resource-tutorial
  type: git
  source:
    uri: {{git-url}}
- name: resource-app
  type: git
  source:
    uri: https://github.com/cloudfoundry-community/simple-go-web-app.git

- name: resource-deploy-web-app
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: true

jobs:
- name: job-deploy-app
  public: true
  serial: true
  plan:
  - get: resource-tutorial
  - get: resource-app
    trigger: true
  - task: update-manifest
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs:
      - name: resource-tutorial
      - name: resource-app
        path: resource-web-app

      outputs:
      - name: cf-manifest

      run:
        path: resource-tutorial/15_deploy_cloudfoundry_app/update-manifest.sh
  - task: web-app-tests
    file: resource-tutorial/10_job_inputs/task_run_tests.yml
  - put: resource-deploy-web-app
    params:
      manifest: cf-manifest/manifest.yml
      path: resource-app
