jobs:
- name: job-dummy
  public: true
  serial: true
  plan:
  - put: resource-dummy
resources:
- name: resource-dummy
  type: dummy

resource_types:
- name: dummy
  type: docker-image
  source:
    repository: starkandwayne/dummy-concourse-resource
